# Generated by Django 6.0.2 on 2026-03-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("matricula", models.CharField(max_length=20)),
                ("curso", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField()),
            ],
        ),
    ]
