# Generated by Django 6.0.2 on 2026-03-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="matricula",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
