# Generated by Django 6.0.2 on 2026-03-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0002_materia"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="materias",
            field=models.ManyToManyField(to="alunos.materia"),
        ),
    ]
