# Generated by Django 6.0.2 on 2026-03-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0003_aluno_materias"),
    ]

    operations = [
        migrations.RenameField(
            model_name="materia",
            old_name="nome",
            new_name="nome_materia",
        ),
    ]
