# Generated by Django 6.0.2 on 2026-03-12 13:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0004_rename_nome_materia_nome_materia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aluno",
            options={"verbose_name": "Aluno", "verbose_name_plural": "Alunos"},
        ),
        migrations.AlterModelOptions(
            name="curso",
            options={"verbose_name": "Curso", "verbose_name_plural": "Cursos"},
        ),
        migrations.AlterModelOptions(
            name="materia",
            options={"verbose_name": "Matéria", "verbose_name_plural": "Matérias"},
        ),
        migrations.AddField(
            model_name="aluno",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="endereco",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="telefone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="curso",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="curso",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="materia",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="materia",
            name="carga_horaria",
            field=models.PositiveIntegerField(
                default=60, help_text="Carga horária em horas"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alunos",
                to="alunos.curso",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="materias",
            field=models.ManyToManyField(
                blank=True, related_name="alunos_matriculados", to="alunos.materia"
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="materia",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materias",
                to="alunos.curso",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="materia",
            unique_together={("nome_materia", "curso")},
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Nota de 0.00 a 10.00",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("data_avaliacao", models.DateField(auto_now_add=True)),
                (
                    "tipo_avaliacao",
                    models.CharField(
                        choices=[
                            ("PROVA", "Prova"),
                            ("TRABALHO", "Trabalho"),
                            ("ATIVIDADE", "Atividade"),
                            ("EXERCICIO", "Exercício"),
                            ("PROJETO", "Projeto"),
                        ],
                        default="PROVA",
                        max_length=20,
                    ),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="alunos.aluno",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="alunos.materia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota",
                "verbose_name_plural": "Notas",
                "ordering": ["-data_avaliacao"],
                "unique_together": {
                    ("aluno", "materia", "data_avaliacao", "tipo_avaliacao")
                },
            },
        ),
    ]
